/* Global source for all protocol buffer c defintions. Autogenerated by build system. Allows all messages to be easily included by other things */
/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.3 */

#include "readings.pb.h"

#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t Sample_fields[12] = {
    PB_FIELD(  1, FIXED32 , REQUIRED, STATIC  , FIRST, Sample, time, time, 0),
    PB_FIELD(  2, FLOAT   , OPTIONAL, STATIC  , OTHER, Sample, batt, time, 0),
    PB_FIELD(  3, FLOAT   , OPTIONAL, STATIC  , OTHER, Sample, temp, batt, 0),
    PB_FIELD(  4, SINT32  , OPTIONAL, STATIC  , OTHER, Sample, accX, temp, 0),
    PB_FIELD(  5, SINT32  , OPTIONAL, STATIC  , OTHER, Sample, accY, accX, 0),
    PB_FIELD(  6, SINT32  , OPTIONAL, STATIC  , OTHER, Sample, accZ, accY, 0),
    PB_FIELD(  7, UINT32  , OPTIONAL, STATIC  , OTHER, Sample, ADC1, accZ, 0),
    PB_FIELD(  8, UINT32  , OPTIONAL, STATIC  , OTHER, Sample, ADC2, ADC1, 0),
    PB_FIELD(  9, UINT32  , OPTIONAL, STATIC  , OTHER, Sample, rain, ADC2, 0),
    PB_FIELD( 10, BYTES   , OPTIONAL, STATIC  , OTHER, Sample, AVR, rain, 0),
    PB_FIELD( 11, UINT32  , REQUIRED, STATIC  , OTHER, Sample, id, AVR, 0),
    PB_LAST_FIELD
};


/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.3 */

#include "rs485_message.pb.h"

#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

const Rs485_Type Rs485_type_default = Rs485_Type_READ;


const pb_field_t Rs485_fields[7] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, Rs485, dst, dst, 0),
    PB_FIELD(  2, ENUM    , REQUIRED, STATIC  , OTHER, Rs485, type, dst, &Rs485_type_default),
    PB_FIELD(  3, ENUM    , OPTIONAL, STATIC  , OTHER, Rs485, sensor, type, 0),
    PB_FIELD(  4, MESSAGE , REPEATED, STATIC  , OTHER, Rs485, ow, sensor, &OwData_fields),
    PB_FIELD(  5, MESSAGE , REPEATED, STATIC  , OTHER, Rs485, ad, ow, &AnalogData_fields),
    PB_FIELD(  6, MESSAGE , REPEATED, STATIC  , OTHER, Rs485, tad, ad, &TempAccelData_fields),
    PB_LAST_FIELD
};

const pb_field_t OwData_fields[3] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, OwData, id, id, 0),
    PB_FIELD(  2, FLOAT   , REQUIRED, STATIC  , OTHER, OwData, value, id, 0),
    PB_LAST_FIELD
};

const pb_field_t AnalogData_fields[3] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, AnalogData, adc, adc, 0),
    PB_FIELD(  2, FLOAT   , REQUIRED, STATIC  , OTHER, AnalogData, value, adc, 0),
    PB_LAST_FIELD
};

const pb_field_t TempAccelData_fields[5] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, TempAccelData, id, id, 0),
    PB_FIELD(  2, FLOAT   , REQUIRED, STATIC  , OTHER, TempAccelData, pitch, id, 0),
    PB_FIELD(  3, FLOAT   , REQUIRED, STATIC  , OTHER, TempAccelData, roll, pitch, 0),
    PB_FIELD(  4, FLOAT   , REQUIRED, STATIC  , OTHER, TempAccelData, temp, roll, 0),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(Rs485, ow[0]) < 65536 && pb_membersize(Rs485, ad[0]) < 65536 && pb_membersize(Rs485, tad[0]) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_Rs485_OwData_AnalogData_TempAccelData)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(Rs485, ow[0]) < 256 && pb_membersize(Rs485, ad[0]) < 256 && pb_membersize(Rs485, tad[0]) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_Rs485_OwData_AnalogData_TempAccelData)
#endif


/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.3 */

#include "settings.pb.h"

#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t SensorConfig_fields[6] = {
    PB_FIELD(  1, BOOL    , REQUIRED, STATIC  , FIRST, SensorConfig, hasADC1, hasADC1, 0),
    PB_FIELD(  2, BOOL    , REQUIRED, STATIC  , OTHER, SensorConfig, hasADC2, hasADC1, 0),
    PB_FIELD(  3, BOOL    , REQUIRED, STATIC  , OTHER, SensorConfig, hasRain, hasADC2, 0),
    PB_FIELD(  4, UINT32  , REPEATED, STATIC  , OTHER, SensorConfig, avrIDs, hasRain, 0),
    PB_FIELD(  5, UINT64  , REQUIRED, STATIC  , OTHER, SensorConfig, interval, avrIDs, 0),
    PB_LAST_FIELD
};


