/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.3 */

#include "power.pb.h"

#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t PowerInfo_fields[2] = {
    PB_FIELD(  1, FLOAT   , OPTIONAL, STATIC  , FIRST, PowerInfo, batt, batt, 0),
    PB_LAST_FIELD
};


