/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.3 */

#ifndef PB_POWER_PB_H_INCLUDED
#define PB_POWER_PB_H_INCLUDED
#include "pb.h"
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
/* Struct definitions */
typedef struct _PowerInfo {
    bool has_batt;
    float batt;
} PowerInfo;

/* Default values for struct fields */

/* Initializer values for message structs */
#define PowerInfo_init_default                   {false, 0}
#define PowerInfo_init_zero                      {false, 0}

/* Field tags (for use in manual encoding/decoding) */
#define PowerInfo_batt_tag                       1

/* Struct field encoding specification for nanopb */
extern const pb_field_t PowerInfo_fields[2];

/* Maximum encoded size of messages (where known) */
#define PowerInfo_size                           5

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define POWER_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
