/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.6 */

#include "readings.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t Sample_fields[14] = {
    PB_FIELD(  1, FIXED32 , REQUIRED, STATIC  , FIRST, Sample, time, time, 0),
    PB_ONEOF_FIELD(battery,   2, FLOAT   , ONEOF, STATIC  , OTHER, Sample, batt, time, 0),
    PB_ONEOF_FIELD(battery,  13, MESSAGE , ONEOF, STATIC  , OTHER, Sample, power, time, &PowerInfo_fields),
    PB_FIELD(  3, FLOAT   , OPTIONAL, STATIC  , OTHER, Sample, temp, battery.power, 0),
    PB_FIELD(  4, SINT32  , OPTIONAL, STATIC  , OTHER, Sample, accX, temp, 0),
    PB_FIELD(  5, SINT32  , OPTIONAL, STATIC  , OTHER, Sample, accY, accX, 0),
    PB_FIELD(  6, SINT32  , OPTIONAL, STATIC  , OTHER, Sample, accZ, accY, 0),
    PB_FIELD(  7, UINT32  , OPTIONAL, STATIC  , OTHER, Sample, ADC1, accZ, 0),
    PB_FIELD(  8, UINT32  , OPTIONAL, STATIC  , OTHER, Sample, ADC2, ADC1, 0),
    PB_FIELD(  9, UINT32  , OPTIONAL, STATIC  , OTHER, Sample, rain, ADC2, 0),
    PB_FIELD( 10, BYTES   , OPTIONAL, STATIC  , OTHER, Sample, AVR, rain, 0),
    PB_FIELD( 11, UINT32  , REQUIRED, STATIC  , OTHER, Sample, id, AVR, 0),
    PB_FIELD( 12, FLOAT   , OPTIONAL, STATIC  , OTHER, Sample, humid, id, 0),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(Sample, battery.power) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_Sample)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(Sample, battery.power) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_Sample)
#endif


/* @@protoc_insertion_point(eof) */
