/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.3 */

#ifndef PB_SETTINGS_PB_H_INCLUDED
#define PB_SETTINGS_PB_H_INCLUDED
#include "pb.h"
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
/* Struct definitions */
typedef struct _POSTConfig {
    pb_size_t ip_count;
    uint32_t ip[8];
    uint32_t port;
    uint64_t interval;
    bool has_offset;
    uint64_t offset;
} POSTConfig;

typedef struct _SensorConfig {
    bool hasADC1;
    bool hasADC2;
    bool hasRain;
    pb_size_t avrIDs_count;
    uint32_t avrIDs[8];
    uint64_t interval;
} SensorConfig;

/* Default values for struct fields */

/* Initializer values for message structs */
#define SensorConfig_init_default                {0, 0, 0, 0, {0, 0, 0, 0, 0, 0, 0, 0}, 0}
#define POSTConfig_init_default                  {0, {0, 0, 0, 0, 0, 0, 0, 0}, 0, 0, false, 0}
#define SensorConfig_init_zero                   {0, 0, 0, 0, {0, 0, 0, 0, 0, 0, 0, 0}, 0}
#define POSTConfig_init_zero                     {0, {0, 0, 0, 0, 0, 0, 0, 0}, 0, 0, false, 0}

/* Field tags (for use in manual encoding/decoding) */
#define POSTConfig_ip_tag                        1
#define POSTConfig_port_tag                      2
#define POSTConfig_interval_tag                  3
#define POSTConfig_offset_tag                    4
#define SensorConfig_hasADC1_tag                 1
#define SensorConfig_hasADC2_tag                 2
#define SensorConfig_hasRain_tag                 3
#define SensorConfig_avrIDs_tag                  4
#define SensorConfig_interval_tag                5

/* Struct field encoding specification for nanopb */
extern const pb_field_t SensorConfig_fields[6];
extern const pb_field_t POSTConfig_fields[5];

/* Maximum encoded size of messages (where known) */
#define SensorConfig_size                        65
#define POSTConfig_size                          76

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define SETTINGS_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
