/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.6 */

#ifndef PB_SETTINGS_PB_H_INCLUDED
#define PB_SETTINGS_PB_H_INCLUDED
#include "pb.h"
/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _SensorConfig_RoutingMode {
    SensorConfig_RoutingMode_MESH = 0,
    SensorConfig_RoutingMode_FEATHER = 1,
    SensorConfig_RoutingMode_LEAF = 2
} SensorConfig_RoutingMode;
#define _SensorConfig_RoutingMode_MIN SensorConfig_RoutingMode_MESH
#define _SensorConfig_RoutingMode_MAX SensorConfig_RoutingMode_LEAF
#define _SensorConfig_RoutingMode_ARRAYSIZE ((SensorConfig_RoutingMode)(SensorConfig_RoutingMode_LEAF+1))

/* Struct definitions */
typedef struct _SensorConfig {
    bool hasADC1;
    bool hasADC2;
    bool hasRain;
    bool has_avrID;
    uint8_t avrID;
    uint32_t interval;
    SensorConfig_RoutingMode routingMode;
    bool has_powerID;
    uint8_t powerID;
/* @@protoc_insertion_point(struct:SensorConfig) */
} SensorConfig;

/* Default values for struct fields */

/* Initializer values for message structs */
#define SensorConfig_init_default                {0, 0, 0, false, 0, 0, (SensorConfig_RoutingMode)0, false, 0}
#define SensorConfig_init_zero                   {0, 0, 0, false, 0, 0, (SensorConfig_RoutingMode)0, false, 0}

/* Field tags (for use in manual encoding/decoding) */
#define SensorConfig_hasADC1_tag                 1
#define SensorConfig_hasADC2_tag                 2
#define SensorConfig_hasRain_tag                 3
#define SensorConfig_avrID_tag                   4
#define SensorConfig_interval_tag                5
#define SensorConfig_routingMode_tag             6
#define SensorConfig_powerID_tag                 7

/* Struct field encoding specification for nanopb */
extern const pb_field_t SensorConfig_fields[8];

/* Maximum encoded size of messages (where known) */
#define SensorConfig_size                        26

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define SETTINGS_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
