# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: power.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='power.proto',
  package='',
  serialized_pb=_b('\n\x0bpower.proto\"E\n\tPowerInfo\x12\x0c\n\x04\x62\x61tt\x18\x01 \x01(\r\x12\x0f\n\x07\x63urrent\x18\x02 \x01(\x05\x12\x0b\n\x03soc\x18\x03 \x01(\r\x12\x0c\n\x04mppt\x18\x04 \x01(\rB\x18\n\x16org.mountainsensing.pb')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_POWERINFO = _descriptor.Descriptor(
  name='PowerInfo',
  full_name='PowerInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='batt', full_name='PowerInfo.batt', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='current', full_name='PowerInfo.current', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='soc', full_name='PowerInfo.soc', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='mppt', full_name='PowerInfo.mppt', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=15,
  serialized_end=84,
)

DESCRIPTOR.message_types_by_name['PowerInfo'] = _POWERINFO

PowerInfo = _reflection.GeneratedProtocolMessageType('PowerInfo', (_message.Message,), dict(
  DESCRIPTOR = _POWERINFO,
  __module__ = 'power_pb2'
  # @@protoc_insertion_point(class_scope:PowerInfo)
  ))
_sym_db.RegisterMessage(PowerInfo)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\026org.mountainsensing.pb'))
# @@protoc_insertion_point(module_scope)
