# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: settings.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='settings.proto',
  package='',
  serialized_pb=_b('\n\x0esettings.proto\"\xd3\x01\n\x0cSensorConfig\x12\x0f\n\x07hasADC1\x18\x01 \x02(\x08\x12\x0f\n\x07hasADC2\x18\x02 \x02(\x08\x12\x0f\n\x07hasRain\x18\x03 \x02(\x08\x12\r\n\x05\x61vrID\x18\x04 \x01(\r\x12\x10\n\x08interval\x18\x05 \x02(\r\x12.\n\x0broutingMode\x18\x06 \x02(\x0e\x32\x19.SensorConfig.RoutingMode\x12\x0f\n\x07powerID\x18\x07 \x01(\r\".\n\x0bRoutingMode\x12\x08\n\x04MESH\x10\x00\x12\x0b\n\x07\x46\x45\x41THER\x10\x01\x12\x08\n\x04LEAF\x10\x02\x42\x18\n\x16org.mountainsensing.pb')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_SENSORCONFIG_ROUTINGMODE = _descriptor.EnumDescriptor(
  name='RoutingMode',
  full_name='SensorConfig.RoutingMode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='MESH', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FEATHER', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LEAF', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=184,
  serialized_end=230,
)
_sym_db.RegisterEnumDescriptor(_SENSORCONFIG_ROUTINGMODE)


_SENSORCONFIG = _descriptor.Descriptor(
  name='SensorConfig',
  full_name='SensorConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='hasADC1', full_name='SensorConfig.hasADC1', index=0,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='hasADC2', full_name='SensorConfig.hasADC2', index=1,
      number=2, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='hasRain', full_name='SensorConfig.hasRain', index=2,
      number=3, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='avrID', full_name='SensorConfig.avrID', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='interval', full_name='SensorConfig.interval', index=4,
      number=5, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='routingMode', full_name='SensorConfig.routingMode', index=5,
      number=6, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='powerID', full_name='SensorConfig.powerID', index=6,
      number=7, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _SENSORCONFIG_ROUTINGMODE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=230,
)

_SENSORCONFIG.fields_by_name['routingMode'].enum_type = _SENSORCONFIG_ROUTINGMODE
_SENSORCONFIG_ROUTINGMODE.containing_type = _SENSORCONFIG
DESCRIPTOR.message_types_by_name['SensorConfig'] = _SENSORCONFIG

SensorConfig = _reflection.GeneratedProtocolMessageType('SensorConfig', (_message.Message,), dict(
  DESCRIPTOR = _SENSORCONFIG,
  __module__ = 'settings_pb2'
  # @@protoc_insertion_point(class_scope:SensorConfig)
  ))
_sym_db.RegisterMessage(SensorConfig)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\026org.mountainsensing.pb'))
# @@protoc_insertion_point(module_scope)
